# Generated by Django 6.0.6 on 2026-06-15 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_year', models.IntegerField()),
                ('publisher', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='brak opisu')),
                ('image', models.ImageField(blank=True, upload_to='games/')),
                ('min_players', models.IntegerField()),
                ('max_players', models.IntegerField()),
                ('min_time', models.IntegerField()),
                ('max_time', models.IntegerField()),
                ('min_age', models.IntegerField()),
                ('genres', models.ManyToManyField(to='catalog.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('text', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.boardgame')),
            ],
        ),
    ]
