# Generated by Django 6.0.6 on 2026-06-22 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_review_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='max_players',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Za mało graczy.'), django.core.validators.MaxValueValidator(20, message='Za dużo graczy (maks. 20).')]),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='max_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(5, message='Minimalny czas to 5 min'), django.core.validators.MaxValueValidator(360, message='Maksymalny czas to 360 min')]),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='min_age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(3, message='Minimalny wiek to 3 lata'), django.core.validators.MaxValueValidator(18, message='Maksymalny wiek to 18 lata')]),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='min_players',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Za mało graczy.'), django.core.validators.MaxValueValidator(20, message='Za dużo graczy (maks. 20).')]),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='min_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(5, message='Minimalny czas to 5 min'), django.core.validators.MaxValueValidator(360, message='Maksymalny czas to 360 min')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
    ]
